abdem=read.csv('C:/Users/harit/Desktop/filterbubblescripts/Metadata/ab_metadata_democrat.csv')
abrep=read.csv('C:/Users/harit/Desktop/filterbubblescripts/Metadata/ab_metadata_republican.csv')
t.test(abdem$dcc,abrep$dcc) 
t.test(abdem$reciprocity,abrep$reciprocity) 
#t.test(abdem$triad_count,abrep$traid_count) 
t.test(abdem$dyad_ratio,abrep$dyad_ratio) 
abrep$tmr=abrep$triad_count/abrep$undirected_tc
abdem$tmr=abdem$triad_count/abdem$undirected_tc
t.test(abdem$tmr,abrep$tmr)

abdemext=read.csv('C:/Users/harit/Desktop/filterbubblescripts/Metadata/metadata_extdemocrat_abortion.csv')
abrepext=read.csv('C:/Users/harit/Desktop/filterbubblescripts/Metadata/metadata_extrepublican_abortion.csv')
t.test(abdemext$dcc,abrepext$dcc) 
t.test(abdemext$reciprocity,abrepext$reciprocity) 
#t.test(abdemext$triad_count,abrepext$traid_count) 
t.test(abdemext$dyad_ratio,abrepext$dyad_ratio) 
abrepext$tmr=abrepext$triad_count/abrepext$undirected_tc
abdemext$tmr=abdemext$triad_count/abdemext$undirected_tc
t.test(abdemext$tmr,abrepext$tmr)
