#setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
#ABORTION DATASET
abdem=read.csv('ab_metadata_democrat.csv')
abrep=read.csv('ab_metadata_republican.csv')
pairs(~dcc +reciprocity+ dyad_ratio + triad_count , data = abdem)
pairs(~dcc +reciprocity+ dyad_ratio + triad_count , data = abrep)

shapiro.test(abdem$dcc) 
shapiro.test(abrep$dcc) 
shapiro.test(abdem$reciprocity) 
shapiro.test(abrep$reciprocity) 
shapiro.test(abdem$dyad_ratio) 
shapiro.test(abrep$dyad_ratio) 
shapiro.test(abdem$triad_count) 
shapiro.test(abrep$triad_count) 
#q-q plots for abortion dataset

qqnorm(abdem$dcc, pch = 1, frame = FALSE)
qqline(abdem$dcc, col = "steelblue", lwd = 2)
qqnorm(abrep$dcc, pch = 1, frame = FALSE)
qqline(abrep$dcc, col = "steelblue", lwd = 2)
qqnorm(abdem$reciprocity, pch = 1, frame = FALSE)
qqline(abdem$reciprocity, col = "steelblue", lwd = 2)
qqnorm(abrep$reciprocity, pch = 1, frame = FALSE)
qqline(abrep$reciprocity, col = "steelblue", lwd = 2)
qqnorm(abdem$dyad_ratio, pch = 1, frame = FALSE)
qqline(abdem$dyad_ratio, col = "steelblue", lwd = 2)
qqnorm(abrep$dyad_ratio, pch = 1, frame = FALSE)
qqline(abrep$dyad_ratio, col = "steelblue", lwd = 2)
#HISTOGRAM for abortion dataset
hist(abdem$dcc,col='green',main='Abortion directed clustering coefficient')
hist(abrep$dcc,col='blue',add=TRUE)
hist(abdem$reciprocity,col='green',main=' Abortion Reciprocity')
hist(abrep$reciprocity,col='blue',add=TRUE)
hist(abdem$undirected_tc,col='green',main='Abortion undirected_tc')
hist(abrep$undirected_tc,col='blue',add=TRUE)
hist(abdem$triad_count,col='green',main='Abortion triad count')
hist(abrep$triad_count,col='blue',add=TRUE)
hist(abdem$dyad_ratio,col='green',main='Abortion dyad ratio')
hist(abrep$dyad_ratio,col='blue',add=TRUE)


#boxplots of each metrics for abortion
boxplot(abdem$dcc,abrep$dcc,ylab = "clustering",names = c("democrat","republican"), main = "DCC metric")
boxplot(abdem$reciprocity,abrep$reciprocity, ylab = "reciprocity",names = c("democrat","republican"),main = "Reciprocity metric")
boxplot(abdem$triad_count,abrep$triad_count,ylab = "triad count",names = c("democrat","republican"), main = "Triad count metric")
boxplot(abdem$dyad_ratio,abrep$dyad_ratio,ylab = "dyad ratio",names = c("democrat","republican"), main = "Dyad ratio metric")
#Statistical t-test for abortion dataset
t.test(abdem$dcc,abrep$dcc) 
t.test(abdem$reciprocity,abrep$reciprocity) 
t.test(abdem$triad_count,abrep$traid_count) 
t.test(abdem$dyad_ratio,abrep$dyad_ratio) 



##GUN CONTROL DATASET
gcdem=read.csv('gc_metadata_democrat.csv')
gcrep=read.csv('gc_metadata_republican.csv')
hist(gcdem$dcc,col='green',main='Gun control directed clustering coefficient')
hist(gcrep$dcc,col='blue',add=TRUE)
hist(gcdem$reciprocity,col='green',main='Gun control Reciprocity')
hist(gcrep$reciprocity,col='blue',add=TRUE)
hist(gcdem$undirected_tc,col='green',main='Gun control undirected_tc')
hist(gcrep$undirected_tc,col='blue',add=TRUE)
hist(gcdem$triad_count,col='green',main='Gun control triad count')
hist(gcrep$triad_count,col='blue',add=TRUE)
hist(gcdem$dyad_ratio,col='green',main='Gun control dyad ratio')
hist(gcrep$dyad_ratio,col='blue',add=TRUE)
#boxplots for gun control
boxplot(gcdem$dcc,gcrep$dcc,ylab = "clustering",names = c("democrat","republican"), main = "DCC metric")
boxplot(gcdem$reciprocity,gcrep$reciprocity, ylab = "reciprocity",names = c("democrat","republican"),main = "Reciprocity metric")
boxplot(gcdem$triad_count,gcrep$triad_count,ylab = "triad count",names = c("democrat","republican"), main = "Triad count metric")
boxplot(gcdem$dyad_ratio,gcrep$dyad_ratio,ylab = "dyad ratio",names = c("democrat","republican"), main = "Dyad ratio metric")
#q-q plots for gun control
qqnorm(gcdem$dcc, pch = 1, frame = FALSE)
qqline(gcdem$dcc, col = "steelblue", lwd = 2)
qqnorm(gcrep$dcc, pch = 1, frame = FALSE)
qqline(gcrep$dcc, col = "steelblue", lwd = 2)
qqnorm(gcdem$reciprocity, pch = 1, frame = FALSE)
qqline(gcdem$reciprocity, col = "steelblue", lwd = 2)
qqnorm(gcrep$reciprocity, pch = 1, frame = FALSE)
qqline(gcrep$reciprocity, col = "steelblue", lwd = 2)
qqnorm(gcdem$dyad_ratio, pch = 1, frame = FALSE)
qqline(gcdem$dyad_ratio, col = "steelblue", lwd = 2)
qqnorm(gcrep$dyad_ratio, pch = 1, frame = FALSE)
qqline(gcrep$dyad_ratio, col = "steelblue", lwd = 2)

# Statistical t test for gun control
t.test(gcdem$dcc,gcrep$dcc) 
t.test(gcdem$reciprocity,gcrep$reciprocity) 
t.test(gcdem$triad_count,gcrep$traid_count) 
t.test(gcdem$dyad_ratio,gcrep$dyad_ratio) 

##OBAMA CARE DATASET

obdem=read.csv('ob_metadata_democrat.csv')
obrep=read.csv('ob_metadata_republican.csv')
hist(obdem$dcc,col='green',main='Obama Care directed clustering coefficient')
hist(obrep$dcc,col='blue',add=TRUE)
hist(obdem$reciprocity,col='green',main='Obama Care Reciprocity')
hist(obrep$reciprocity,col='blue',add=TRUE)
hist(obdem$undirected_tc,col='green',main='Obama Care undirected_tc')
hist(obrep$undirected_tc,col='blue',add=TRUE)
hist(obdem$triad_count,col='green',main='Obama Care triad count')
hist(obrep$triad_count,col='blue',add=TRUE)
hist(obdem$dyad_ratio,col='green',main='Obama Care dyad ratio')
hist(obrep$dyad_ratio,col='blue',add=TRUE)
#boxplot obama care dataset
boxplot(obdem$dcc,obrep$dcc,ylab = "clustering",names = c("democrat","republican"), main = "DCC metric")
boxplot(obdem$reciprocity,obrep$reciprocity, ylab = "reciprocity",names = c("democrat","republican"),main = "Reciprocity metric")
boxplot(obdem$triad_count,obrep$triad_count,ylab = "triad count",names = c("democrat","republican"), main = "Triad count metric")
boxplot(obdem$dyad_ratio,obrep$dyad_ratio,ylab = "dyad ratio",names = c("democrat","republican"), main = "Dyad ratio metric")
#q-q plots for obama care
qqnorm(obdem$dcc, pch = 1, frame = FALSE)
qqline(obdem$dcc, col = "steelblue", lwd = 2)
qqnorm(obrep$dcc, pch = 1, frame = FALSE)
qqline(obrep$dcc, col = "steelblue", lwd = 2)
qqnorm(obdem$reciprocity, pch = 1, frame = FALSE)
qqline(obdem$reciprocity, col = "steelblue", lwd = 2)
qqnorm(obrep$reciprocity, pch = 1, frame = FALSE)
qqline(obrep$reciprocity, col = "steelblue", lwd = 2)
qqnorm(obdem$dyad_ratio, pch = 1, frame = FALSE)
qqline(obdem$dyad_ratio, col = "steelblue", lwd = 2)
qqnorm(obrep$dyad_ratio, pch = 1, frame = FALSE)
qqline(obrep$dyad_ratio, col = "steelblue", lwd = 2)

#Statistical t test for obama care
t.test(obdem$dcc,obrep$dcc) 
t.test(obdem$reciprocity,obrep$reciprocity) 
t.test(obdem$triad_count,obrep$traid_count) 
t.test(obdem$dyad_ratio,obrep$dyad_ratio) 
